<?php

array:2 [
    0 => array:1 [
    0 => array:115 [
    "id" => 6
      "company_id" => 34
      "name" => "ավտովարկ test 2"
      "copy" => null
      "edit" => null
      "status" => 1
      "curr_row_old_data" => null
      "active_time_type" => null
      "checked_special_projects" => null
      "checked_documents_types" => "2"
      "checker_admin_id" => null
      "author_id" => 89
      "belonging_id" => 1
      "car_type" => 2
      "prepayment" => "1"
      "loan_amount_from" => "1"
      "loan_amount_to" => "1"
      "prepayment_to" => null
      "prepayment_from" => null
      "loan_term_from" => "1"
      "loan_term_to" => "1"
      "loan_term_to_in_days" => "30"
      "loan_term_from_in_days" => "1"
      "loan_term_from_periodicity_type" => 1
      "loan_term_to_periodicity_type" => 2
      "privileged_term" => null
      "privileged_term_loan" => null
      "privileged_term_loan_time_type" => null
      "privileged_term_percentage_time_type" => null
      "privileged_term_percentage" => null
      "checked_repayment_types" => "2"
      "providing_type" => 2
      "percentage_type" => 1
      "percentage_rate_type" => null
      "nominal_percentage_rate" => null
      "car_salone_loan_phone" => null
      "car_salone_loan_address" => null
      "car_salone_loan_name" => null
      "service_on_company_website" => "http://cbapro/edit-product/1/1"
      "loan_main_amount_non_payment_case" => "Վարկի մայր գումարը չվճարելու դեպքում"
      "loan_main_amount_non_payment_case_old" => null
      "percentage_sum_non_payment_case" => "Տոկոսագումարները չվճարելու դեպքում"
      "another_non_payments_case" => "Այլ վճարները չկատարելու դեպքում"
      "another_non_payments_case_old" => null
      "other_non_payment" => "Այլ"
      "security" => null
      "special_projects" => 0
      "special_project_name" => null
      "more_information" => null
      "notarial_ratification_pay" => "1"
      "notarial_ratification_pay_from" => "1"
      "notarial_ratification_pay_to" => "1"
      "pledge_insurance_pay_type" => 2
      "pledge_insurance_pay_for_type" => null
      "pledge_insurance_pay_from" => "1"
      "pledge_insurance_pay_to" => "1"
      "loan_service_pay_type" => 1
      "loan_service_pay_for_type" => null
      "loan_service_pay_from" => "1"
      "loan_service_pay_to" => null
      "pledge_assessment_pay_once_type" => null
      "pledge_assessment_pay_from" => "1"
      "pledge_assessment_pay_to" => "1"
      "cashing_pay_type" => null
      "cashing_pay_from" => "1"
      "cashing_pay_to" => "1"
      "loan_application_survey_pay_type" => null
      "loan_application_survey_pay_from" => "1"
      "loan_application_survey_pay_to" => "1"
      "other_payments_sum_type" => null
      "security_type" => null
      "other_payments_sum_percent_type" => null
      "other_payments_name" => null
      "other_payments_periodicity" => 0
      "other_payments_absolute_amount" => null
      "other_payments_to" => null
      "other_payments_from" => null
      "documents_list_area" => null
      "more_special_projects" => null
      "deposit_message" => null
      "activate_date" => null
      "active_date" => null
      "auto_show_name" => null
      "auto_show_address" => null
      "auto_show_phone" => null
      "created_at" => "2018-07-27 15:49:46"
      "updated_at" => "2018-07-27 15:49:46"
      "repayment_loan_interval_types" => null
      "repayment_percent_interval_types" => null
      "percentage_fixed" => "2"
      "percentage_changing_from" => "4"
      "percentage_changing_to" => "2"
      "percentage_changing_in" => "3"
      "percentage_changing_concret_to" => "6"
      "percentage_changing_concret_from" => "2"
      "security_types" => null
      "other_payments" => null
      "car_salons" => null
      "special_project_percent" => null
      "documents_list" => null
      "document_name" => "njhhhgjghj"
      "privileged_term_checked" => null
      "checked_repayment_loan_interval_types" => "0"
      "checked_repayment_percent_interval_types" => "0"
      "other_payments_checked" => null
      "checked_security_types" => "1,2"
      "loan_application_absolute_amount" => "1"
      "loan_service_absolute_amount" => "1"
      "pledge_assessment_absolute_amount" => "1"
      "cashing_pay_absolute_amount" => "1"
      "pledge_insurance_absolute_amount" => "1"
      "company_info" => array:33 [
    "id" => 34
        "around_the_clock_working" => null
        "name" => "qqqqqqqqqqqqqqqqqqqqqqqq"
        "type" => 1
        "company_superadmin_id" => 90
        "city" => null
        "extra" => ""
        "identity" => "1"
        "address" => "qqqqqqqqqqqqqqqqqqqqqqqqqqqq"
        "phone_number" => null
        "phone_number_2" => null
        "image" => "company/1523285816.jpg"
        "email" => "qqqqqqqqqqqqqqqqqqqqqq@gmail.com"
        "website" => "http://cbaproject/create-company"
        "workingDays" => null
        "sundayWorkEndTime" => null
        "sundayWorkStartTime" => null
        "saturdayWorkEndTime" => null
        "saturdayWorkStartTime" => null
        "fridayWorkEndTime" => null
        "fridayWorkStartTime" => null
        "thursdayWorkEndTime" => null
        "thursdayWorkStartTime" => null
        "wednesdayWorkEndTime" => null
        "wednesdayWorkStartTime" => null
        "tuesdayWorkEndTime" => null
        "tuesdayWorkStartTime" => null
        "mondayWorkEndTime" => null
        "mondayWorkStartTime" => null
        "stateEnd" => null
        "stateStart" => null
        "created_at" => "2018-06-23 06:36:04"
        "updated_at" => "2018-06-23 06:36:04"
      ]
      "car_info" => array:6 [
    "id" => 2
        "name" => "երկրորդային շուկա"
        "icon" => null
        "extra" => null
        "created_at" => null
        "updated_at" => null
      ]
      "loan_term_from_periodicity_type_info" => array:6 [
    "id" => 1
        "name" => "Օր"
        "icon" => null
        "extra" => null
        "created_at" => null
        "updated_at" => null
      ]
      "loan_term_to_periodicity_type_info" => array:6 [
    "id" => 2
        "name" => "Ամիս"
        "icon" => null
        "extra" => null
        "created_at" => null
        "updated_at" => null
      ]
    ]
  ]
  1 => array:6 [
    1 => array:115 [
    "id" => 7
      "company_id" => 33
      "name" => "aaa"
      "copy" => null
      "edit" => null
      "status" => 1
      "curr_row_old_data" => null
      "active_time_type" => null
      "checked_special_projects" => null
      "checked_documents_types" => "2,3"
      "checker_admin_id" => null
      "author_id" => 89
      "belonging_id" => 1
      "car_type" => 2
      "prepayment" => null
      "loan_amount_from" => "1"
      "loan_amount_to" => "2"
      "prepayment_to" => null
      "prepayment_from" => null
      "loan_term_from" => "1"
      "loan_term_to" => "2"
      "loan_term_to_in_days" => "60"
      "loan_term_from_in_days" => "1"
      "loan_term_from_periodicity_type" => 1
      "loan_term_to_periodicity_type" => 2
      "privileged_term" => null
      "privileged_term_loan" => null
      "privileged_term_loan_time_type" => null
      "privileged_term_percentage_time_type" => null
      "privileged_term_percentage" => null
      "checked_repayment_types" => "2"
      "providing_type" => 1
      "percentage_type" => 3
      "percentage_rate_type" => null
      "nominal_percentage_rate" => null
      "car_salone_loan_phone" => null
      "car_salone_loan_address" => null
      "car_salone_loan_name" => null
      "service_on_company_website" => "http://cbaproject/create-product/8"
      "loan_main_amount_non_payment_case" => "Վարկի մայր գումարը չվճարելու դեպքում 1"
      "loan_main_amount_non_payment_case_old" => null
      "percentage_sum_non_payment_case" => "Տոկոսագումարները չվճարելու դեպքում 1"
      "another_non_payments_case" => "Այլ վճարները չկատարելու դեպքում 1"
      "another_non_payments_case_old" => null
      "other_non_payment" => "Այլ"
      "security" => null
      "special_projects" => 0
      "special_project_name" => null
      "more_information" => null
      "notarial_ratification_pay" => "1"
      "notarial_ratification_pay_from" => "1"
      "notarial_ratification_pay_to" => "1"
      "pledge_insurance_pay_type" => 1
      "pledge_insurance_pay_for_type" => null
      "pledge_insurance_pay_from" => "1"
      "pledge_insurance_pay_to" => "1"
      "loan_service_pay_type" => 1
      "loan_service_pay_for_type" => null
      "loan_service_pay_from" => "1"
      "loan_service_pay_to" => null
      "pledge_assessment_pay_once_type" => null
      "pledge_assessment_pay_from" => "1"
      "pledge_assessment_pay_to" => "1"
      "cashing_pay_type" => null
      "cashing_pay_from" => "1"
      "cashing_pay_to" => "1"
      "loan_application_survey_pay_type" => null
      "loan_application_survey_pay_from" => "1"
      "loan_application_survey_pay_to" => "1"
      "other_payments_sum_type" => null
      "security_type" => null
      "other_payments_sum_percent_type" => null
      "other_payments_name" => null
      "other_payments_periodicity" => 0
      "other_payments_absolute_amount" => null
      "other_payments_to" => null
      "other_payments_from" => null
      "documents_list_area" => null
      "more_special_projects" => null
      "deposit_message" => "e"
      "activate_date" => null
      "active_date" => null
      "auto_show_name" => null
      "auto_show_address" => null
      "auto_show_phone" => null
      "created_at" => "2018-08-05 22:20:17"
      "updated_at" => "2018-08-05 22:20:17"
      "repayment_loan_interval_types" => null
      "repayment_percent_interval_types" => null
      "percentage_fixed" => null
      "percentage_changing_from" => "3"
      "percentage_changing_to" => "2"
      "percentage_changing_in" => "3"
      "percentage_changing_concret_to" => "5"
      "percentage_changing_concret_from" => "1"
      "security_types" => null
      "other_payments" => null
      "car_salons" => null
      "special_project_percent" => null
      "documents_list" => null
      "document_name" => "aaaaaaaaaaaa"
      "privileged_term_checked" => null
      "checked_repayment_loan_interval_types" => "0"
      "checked_repayment_percent_interval_types" => "0"
      "other_payments_checked" => null
      "checked_security_types" => "1,3"
      "loan_application_absolute_amount" => "1"
      "loan_service_absolute_amount" => "1"
      "pledge_assessment_absolute_amount" => "1"
      "cashing_pay_absolute_amount" => "1"
      "pledge_insurance_absolute_amount" => "1"
      "company_info" => array:33 [
    "id" => 33
        "around_the_clock_working" => null
        "name" => "ccccccccccccccc"
        "type" => 1
        "company_superadmin_id" => 85
        "city" => null
        "extra" => ""
        "identity" => "1"
        "address" => "cccccccccc"
        "phone_number" => "sdfsdf"
        "phone_number_2" => null
        "image" => "company/1526046056.jpg"
        "email" => "dd@gmai.com"
        "website" => null
        "workingDays" => null
        "sundayWorkEndTime" => null
        "sundayWorkStartTime" => null
        "saturdayWorkEndTime" => null
        "saturdayWorkStartTime" => null
        "fridayWorkEndTime" => null
        "fridayWorkStartTime" => null
        "thursdayWorkEndTime" => null
        "thursdayWorkStartTime" => null
        "wednesdayWorkEndTime" => null
        "wednesdayWorkStartTime" => null
        "tuesdayWorkEndTime" => null
        "tuesdayWorkStartTime" => null
        "mondayWorkEndTime" => null
        "mondayWorkStartTime" => null
        "stateEnd" => null
        "stateStart" => null
        "created_at" => "2018-06-18 18:28:56"
        "updated_at" => "2018-06-19 14:51:55"
      ]
      "car_info" => array:6 [
    "id" => 2
        "name" => "երկրորդային շուկա"
        "icon" => null
        "extra" => null
        "created_at" => null
        "updated_at" => null
      ]
      "loan_term_from_periodicity_type_info" => array:6 [
    "id" => 1
        "name" => "Օր"
        "icon" => null
        "extra" => null
        "created_at" => null
        "updated_at" => null
      ]
      "loan_term_to_periodicity_type_info" => array:6 [
    "id" => 2
        "name" => "Ամիս"
        "icon" => null
        "extra" => null
        "created_at" => null
        "updated_at" => null
      ]
    ]
    2 => array:115 [
    "id" => 8
      "company_id" => 33
      "name" => "sevagir ԱՎՏՈՎԱՐԿ"
      "copy" => null
      "edit" => null
      "status" => 1
      "curr_row_old_data" => null
      "active_time_type" => null
      "checked_special_projects" => null
      "checked_documents_types" => "2,3"
      "checker_admin_id" => null
      "author_id" => 89
      "belonging_id" => 1
      "car_type" => 1
      "prepayment" => null
      "loan_amount_from" => "1"
      "loan_amount_to" => null
      "prepayment_to" => null
      "prepayment_from" => null
      "loan_term_from" => "0"
      "loan_term_to" => "0"
      "loan_term_to_in_days" => null
      "loan_term_from_in_days" => null
      "loan_term_from_periodicity_type" => 0
      "loan_term_to_periodicity_type" => 0
      "privileged_term" => null
      "privileged_term_loan" => null
      "privileged_term_loan_time_type" => null
      "privileged_term_percentage_time_type" => null
      "privileged_term_percentage" => null
      "checked_repayment_types" => "3"
      "providing_type" => 2
      "percentage_type" => null
      "percentage_rate_type" => null
      "nominal_percentage_rate" => null
      "car_salone_loan_phone" => null
      "car_salone_loan_address" => null
      "car_salone_loan_name" => null
      "service_on_company_website" => "http://cbaproject/create-product/8"
      "loan_main_amount_non_payment_case" => "Վարկի մայր գումարը չվճարելու դեպքում 1"
      "loan_main_amount_non_payment_case_old" => null
      "percentage_sum_non_payment_case" => "Տոկոսագումարները չվճարելու դեպքում 1"
      "another_non_payments_case" => "Այլ վճարները չկատարելու դեպքում 1"
      "another_non_payments_case_old" => null
      "other_non_payment" => "Այլ"
      "security" => null
      "special_projects" => 0
      "special_project_name" => null
      "more_information" => "aaaaaaaaaaaaaaaaaa"
      "notarial_ratification_pay" => null
      "notarial_ratification_pay_from" => null
      "notarial_ratification_pay_to" => null
      "pledge_insurance_pay_type" => null
      "pledge_insurance_pay_for_type" => null
      "pledge_insurance_pay_from" => null
      "pledge_insurance_pay_to" => null
      "loan_service_pay_type" => null
      "loan_service_pay_for_type" => null
      "loan_service_pay_from" => null
      "loan_service_pay_to" => null
      "pledge_assessment_pay_once_type" => null
      "pledge_assessment_pay_from" => null
      "pledge_assessment_pay_to" => null
      "cashing_pay_type" => null
      "cashing_pay_from" => null
      "cashing_pay_to" => null
      "loan_application_survey_pay_type" => null
      "loan_application_survey_pay_from" => null
      "loan_application_survey_pay_to" => null
      "other_payments_sum_type" => null
      "security_type" => null
      "other_payments_sum_percent_type" => null
      "other_payments_name" => null
      "other_payments_periodicity" => 0
      "other_payments_absolute_amount" => null
      "other_payments_to" => null
      "other_payments_from" => null
      "documents_list_area" => null
      "more_special_projects" => null
      "deposit_message" => "aaaaaaaaaaaaaaaaaaaaa"
      "activate_date" => 0
      "active_date" => "08/06/2018"
      "auto_show_name" => null
      "auto_show_address" => null
      "auto_show_phone" => null
      "created_at" => "2018-08-05 22:59:45"
      "updated_at" => "2018-08-05 22:59:45"
      "repayment_loan_interval_types" => null
      "repayment_percent_interval_types" => null
      "percentage_fixed" => null
      "percentage_changing_from" => null
      "percentage_changing_to" => null
      "percentage_changing_in" => null
      "percentage_changing_concret_to" => "0"
      "percentage_changing_concret_from" => "0"
      "security_types" => null
      "other_payments" => null
      "car_salons" => null
      "special_project_percent" => null
      "documents_list" => null
      "document_name" => "ԱՎՏՈՎԱՐԿ pastatuxt"
      "privileged_term_checked" => null
      "checked_repayment_loan_interval_types" => "0"
      "checked_repayment_percent_interval_types" => "0"
      "other_payments_checked" => null
      "checked_security_types" => "1,2"
      "loan_application_absolute_amount" => null
      "loan_service_absolute_amount" => null
      "pledge_assessment_absolute_amount" => null
      "cashing_pay_absolute_amount" => null
      "pledge_insurance_absolute_amount" => null
      "company_info" => array:33 [
    "id" => 33
        "around_the_clock_working" => null
        "name" => "ccccccccccccccc"
        "type" => 1
        "company_superadmin_id" => 85
        "city" => null
        "extra" => ""
        "identity" => "1"
        "address" => "cccccccccc"
        "phone_number" => "sdfsdf"
        "phone_number_2" => null
        "image" => "company/1526046056.jpg"
        "email" => "dd@gmai.com"
        "website" => null
        "workingDays" => null
        "sundayWorkEndTime" => null
        "sundayWorkStartTime" => null
        "saturdayWorkEndTime" => null
        "saturdayWorkStartTime" => null
        "fridayWorkEndTime" => null
        "fridayWorkStartTime" => null
        "thursdayWorkEndTime" => null
        "thursdayWorkStartTime" => null
        "wednesdayWorkEndTime" => null
        "wednesdayWorkStartTime" => null
        "tuesdayWorkEndTime" => null
        "tuesdayWorkStartTime" => null
        "mondayWorkEndTime" => null
        "mondayWorkStartTime" => null
        "stateEnd" => null
        "stateStart" => null
        "created_at" => "2018-06-18 18:28:56"
        "updated_at" => "2018-06-19 14:51:55"
      ]
      "car_info" => array:6 [
    "id" => 1
        "name" => "առաջնային շուկա"
        "icon" => null
        "extra" => null
        "created_at" => null
        "updated_at" => null
      ]
      "loan_term_from_periodicity_type_info" => null
      "loan_term_to_periodicity_type_info" => null
    ]
    3 => array:115 [
    "id" => 12
      "company_id" => 33
      "name" => "sevagir ԱՎՏՈՎԱՐԿ 2"
      "copy" => null
      "edit" => null
      "status" => 1
      "curr_row_old_data" => null
      "active_time_type" => null
      "checked_special_projects" => null
      "checked_documents_types" => "2,3"
      "checker_admin_id" => null
      "author_id" => 89
      "belonging_id" => 1
      "car_type" => 1
      "prepayment" => null
      "loan_amount_from" => "1"
      "loan_amount_to" => null
      "prepayment_to" => "7"
      "prepayment_from" => "3"
      "loan_term_from" => "0"
      "loan_term_to" => "0"
      "loan_term_to_in_days" => null
      "loan_term_from_in_days" => null
      "loan_term_from_periodicity_type" => 0
      "loan_term_to_periodicity_type" => 0
      "privileged_term" => null
      "privileged_term_loan" => null
      "privileged_term_loan_time_type" => null
      "privileged_term_percentage_time_type" => null
      "privileged_term_percentage" => null
      "checked_repayment_types" => "3"
      "providing_type" => 2
      "percentage_type" => null
      "percentage_rate_type" => null
      "nominal_percentage_rate" => null
      "car_salone_loan_phone" => null
      "car_salone_loan_address" => null
      "car_salone_loan_name" => null
      "service_on_company_website" => "http://cbaproject/create-product/8"
      "loan_main_amount_non_payment_case" => "Վարկի մայր գումարը չվճարելու դեպքում 1"
      "loan_main_amount_non_payment_case_old" => null
      "percentage_sum_non_payment_case" => "Տոկոսագումարները չվճարելու դեպքում 1"
      "another_non_payments_case" => "Այլ վճարները չկատարելու դեպքում 1"
      "another_non_payments_case_old" => null
      "other_non_payment" => "Այլ"
      "security" => null
      "special_projects" => 0
      "special_project_name" => null
      "more_information" => "aaaaaaaaaaaaaaaaaa"
      "notarial_ratification_pay" => null
      "notarial_ratification_pay_from" => null
      "notarial_ratification_pay_to" => null
      "pledge_insurance_pay_type" => null
      "pledge_insurance_pay_for_type" => null
      "pledge_insurance_pay_from" => null
      "pledge_insurance_pay_to" => null
      "loan_service_pay_type" => null
      "loan_service_pay_for_type" => null
      "loan_service_pay_from" => null
      "loan_service_pay_to" => null
      "pledge_assessment_pay_once_type" => null
      "pledge_assessment_pay_from" => null
      "pledge_assessment_pay_to" => null
      "cashing_pay_type" => null
      "cashing_pay_from" => null
      "cashing_pay_to" => null
      "loan_application_survey_pay_type" => null
      "loan_application_survey_pay_from" => null
      "loan_application_survey_pay_to" => null
      "other_payments_sum_type" => null
      "security_type" => null
      "other_payments_sum_percent_type" => null
      "other_payments_name" => null
      "other_payments_periodicity" => 0
      "other_payments_absolute_amount" => null
      "other_payments_to" => null
      "other_payments_from" => null
      "documents_list_area" => null
      "more_special_projects" => null
      "deposit_message" => "aaaaaaaaaaaaaaaaaaaaa"
      "activate_date" => 0
      "active_date" => "08/06/2018"
      "auto_show_name" => null
      "auto_show_address" => null
      "auto_show_phone" => null
      "created_at" => "2018-08-05 22:59:45"
      "updated_at" => "2018-08-05 22:59:45"
      "repayment_loan_interval_types" => null
      "repayment_percent_interval_types" => null
      "percentage_fixed" => null
      "percentage_changing_from" => null
      "percentage_changing_to" => null
      "percentage_changing_in" => null
      "percentage_changing_concret_to" => "0"
      "percentage_changing_concret_from" => "0"
      "security_types" => null
      "other_payments" => null
      "car_salons" => null
      "special_project_percent" => null
      "documents_list" => null
      "document_name" => "ԱՎՏՈՎԱՐԿ pastatuxt"
      "privileged_term_checked" => null
      "checked_repayment_loan_interval_types" => "0"
      "checked_repayment_percent_interval_types" => "0"
      "other_payments_checked" => null
      "checked_security_types" => "1,2"
      "loan_application_absolute_amount" => null
      "loan_service_absolute_amount" => null
      "pledge_assessment_absolute_amount" => null
      "cashing_pay_absolute_amount" => null
      "pledge_insurance_absolute_amount" => null
      "company_info" => array:33 [
    "id" => 33
        "around_the_clock_working" => null
        "name" => "ccccccccccccccc"
        "type" => 1
        "company_superadmin_id" => 85
        "city" => null
        "extra" => ""
        "identity" => "1"
        "address" => "cccccccccc"
        "phone_number" => "sdfsdf"
        "phone_number_2" => null
        "image" => "company/1526046056.jpg"
        "email" => "dd@gmai.com"
        "website" => null
        "workingDays" => null
        "sundayWorkEndTime" => null
        "sundayWorkStartTime" => null
        "saturdayWorkEndTime" => null
        "saturdayWorkStartTime" => null
        "fridayWorkEndTime" => null
        "fridayWorkStartTime" => null
        "thursdayWorkEndTime" => null
        "thursdayWorkStartTime" => null
        "wednesdayWorkEndTime" => null
        "wednesdayWorkStartTime" => null
        "tuesdayWorkEndTime" => null
        "tuesdayWorkStartTime" => null
        "mondayWorkEndTime" => null
        "mondayWorkStartTime" => null
        "stateEnd" => null
        "stateStart" => null
        "created_at" => "2018-06-18 18:28:56"
        "updated_at" => "2018-06-19 14:51:55"
      ]
      "car_info" => array:6 [
    "id" => 1
        "name" => "առաջնային շուկա"
        "icon" => null
        "extra" => null
        "created_at" => null
        "updated_at" => null
      ]
      "loan_term_from_periodicity_type_info" => null
      "loan_term_to_periodicity_type_info" => null
    ]
    4 => array:115 [
    "id" => 13
      "company_id" => 33
      "name" => "ԱՎՏՈՎԱՐԿ security test"
      "copy" => null
      "edit" => null
      "status" => 1
      "curr_row_old_data" => null
      "active_time_type" => null
      "checked_special_projects" => null
      "checked_documents_types" => "2,3"
      "checker_admin_id" => null
      "author_id" => 89
      "belonging_id" => 1
      "car_type" => 1
      "prepayment" => null
      "loan_amount_from" => "1"
      "loan_amount_to" => "2"
      "prepayment_to" => null
      "prepayment_from" => null
      "loan_term_from" => "1"
      "loan_term_to" => "2"
      "loan_term_to_in_days" => "60"
      "loan_term_from_in_days" => "1"
      "loan_term_from_periodicity_type" => 1
      "loan_term_to_periodicity_type" => 2
      "privileged_term" => null
      "privileged_term_loan" => null
      "privileged_term_loan_time_type" => null
      "privileged_term_percentage_time_type" => null
      "privileged_term_percentage" => null
      "checked_repayment_types" => "3"
      "providing_type" => 2
      "percentage_type" => 2
      "percentage_rate_type" => null
      "nominal_percentage_rate" => null
      "car_salone_loan_phone" => null
      "car_salone_loan_address" => null
      "car_salone_loan_name" => null
      "service_on_company_website" => "http://cbapro/edit-product/1/1"
      "loan_main_amount_non_payment_case" => "Վարկի մայր գումարը չվճարելու դեպքում"
      "loan_main_amount_non_payment_case_old" => null
      "percentage_sum_non_payment_case" => "Տոկոսագումարները չվճարելու դեպքում"
      "another_non_payments_case" => "Այլ վճարները չկատարելու դեպքում"
      "another_non_payments_case_old" => null
      "other_non_payment" => "Այլ"
      "security" => null
      "special_projects" => 0
      "special_project_name" => null
      "more_information" => null
      "notarial_ratification_pay" => "1"
      "notarial_ratification_pay_from" => "1"
      "notarial_ratification_pay_to" => "1"
      "pledge_insurance_pay_type" => 1
      "pledge_insurance_pay_for_type" => null
      "pledge_insurance_pay_from" => "1"
      "pledge_insurance_pay_to" => "1"
      "loan_service_pay_type" => 1
      "loan_service_pay_for_type" => null
      "loan_service_pay_from" => "1"
      "loan_service_pay_to" => null
      "pledge_assessment_pay_once_type" => null
      "pledge_assessment_pay_from" => "1"
      "pledge_assessment_pay_to" => "1"
      "cashing_pay_type" => null
      "cashing_pay_from" => "1"
      "cashing_pay_to" => "1"
      "loan_application_survey_pay_type" => null
      "loan_application_survey_pay_from" => "1"
      "loan_application_survey_pay_to" => "1"
      "other_payments_sum_type" => null
      "security_type" => null
      "other_payments_sum_percent_type" => null
      "other_payments_name" => null
      "other_payments_periodicity" => 0
      "other_payments_absolute_amount" => null
      "other_payments_to" => null
      "other_payments_from" => null
      "documents_list_area" => null
      "more_special_projects" => null
      "deposit_message" => null
      "activate_date" => null
      "active_date" => "08/10/2018"
      "auto_show_name" => null
      "auto_show_address" => null
      "auto_show_phone" => null
      "created_at" => "2018-08-10 12:25:18"
      "updated_at" => "2018-08-10 12:25:18"
      "repayment_loan_interval_types" => null
      "repayment_percent_interval_types" => null
      "percentage_fixed" => null
      "percentage_changing_from" => null
      "percentage_changing_to" => null
      "percentage_changing_in" => "1"
      "percentage_changing_concret_to" => null
      "percentage_changing_concret_from" => null
      "security_types" => null
      "other_payments" => null
      "car_salons" => null
      "special_project_percent" => null
      "documents_list" => null
      "document_name" => "ԱՎՏՈՎԱՐԿ security test"
      "privileged_term_checked" => null
      "checked_repayment_loan_interval_types" => "0"
      "checked_repayment_percent_interval_types" => "0"
      "other_payments_checked" => null
      "checked_security_types" => "1,2"
      "loan_application_absolute_amount" => "1"
      "loan_service_absolute_amount" => "1"
      "pledge_assessment_absolute_amount" => "1"
      "cashing_pay_absolute_amount" => "1"
      "pledge_insurance_absolute_amount" => "1"
      "company_info" => array:33 [
    "id" => 33
        "around_the_clock_working" => null
        "name" => "ccccccccccccccc"
        "type" => 1
        "company_superadmin_id" => 85
        "city" => null
        "extra" => ""
        "identity" => "1"
        "address" => "cccccccccc"
        "phone_number" => "sdfsdf"
        "phone_number_2" => null
        "image" => "company/1526046056.jpg"
        "email" => "dd@gmai.com"
        "website" => null
        "workingDays" => null
        "sundayWorkEndTime" => null
        "sundayWorkStartTime" => null
        "saturdayWorkEndTime" => null
        "saturdayWorkStartTime" => null
        "fridayWorkEndTime" => null
        "fridayWorkStartTime" => null
        "thursdayWorkEndTime" => null
        "thursdayWorkStartTime" => null
        "wednesdayWorkEndTime" => null
        "wednesdayWorkStartTime" => null
        "tuesdayWorkEndTime" => null
        "tuesdayWorkStartTime" => null
        "mondayWorkEndTime" => null
        "mondayWorkStartTime" => null
        "stateEnd" => null
        "stateStart" => null
        "created_at" => "2018-06-18 18:28:56"
        "updated_at" => "2018-06-19 14:51:55"
      ]
      "car_info" => array:6 [
    "id" => 1
        "name" => "առաջնային շուկա"
        "icon" => null
        "extra" => null
        "created_at" => null
        "updated_at" => null
      ]
      "loan_term_from_periodicity_type_info" => array:6 [
    "id" => 1
        "name" => "Օր"
        "icon" => null
        "extra" => null
        "created_at" => null
        "updated_at" => null
      ]
      "loan_term_to_periodicity_type_info" => array:6 [
    "id" => 2
        "name" => "Ամիս"
        "icon" => null
        "extra" => null
        "created_at" => null
        "updated_at" => null
      ]
    ]
    5 => array:115 [
    "id" => 14
      "company_id" => 33
      "name" => "aaaaaaaaaaaaaaaaaaaaaaaaaa"
      "copy" => null
      "edit" => null
      "status" => 1
      "curr_row_old_data" => null
      "active_time_type" => null
      "checked_special_projects" => null
      "checked_documents_types" => null
      "checker_admin_id" => null
      "author_id" => 89
      "belonging_id" => 1
      "car_type" => null
      "prepayment" => null
      "loan_amount_from" => null
      "loan_amount_to" => null
      "prepayment_to" => null
      "prepayment_from" => null
      "loan_term_from" => "0"
      "loan_term_to" => "0"
      "loan_term_to_in_days" => null
      "loan_term_from_in_days" => null
      "loan_term_from_periodicity_type" => 0
      "loan_term_to_periodicity_type" => 0
      "privileged_term" => null
      "privileged_term_loan" => null
      "privileged_term_loan_time_type" => null
      "privileged_term_percentage_time_type" => null
      "privileged_term_percentage" => null
      "checked_repayment_types" => null
      "providing_type" => 0
      "percentage_type" => null
      "percentage_rate_type" => null
      "nominal_percentage_rate" => null
      "car_salone_loan_phone" => null
      "car_salone_loan_address" => null
      "car_salone_loan_name" => null
      "service_on_company_website" => null
      "loan_main_amount_non_payment_case" => null
      "loan_main_amount_non_payment_case_old" => null
      "percentage_sum_non_payment_case" => null
      "another_non_payments_case" => null
      "another_non_payments_case_old" => null
      "other_non_payment" => null
      "security" => null
      "special_projects" => 0
      "special_project_name" => null
      "more_information" => null
      "notarial_ratification_pay" => null
      "notarial_ratification_pay_from" => null
      "notarial_ratification_pay_to" => null
      "pledge_insurance_pay_type" => null
      "pledge_insurance_pay_for_type" => null
      "pledge_insurance_pay_from" => null
      "pledge_insurance_pay_to" => null
      "loan_service_pay_type" => null
      "loan_service_pay_for_type" => null
      "loan_service_pay_from" => null
      "loan_service_pay_to" => null
      "pledge_assessment_pay_once_type" => null
      "pledge_assessment_pay_from" => null
      "pledge_assessment_pay_to" => null
      "cashing_pay_type" => null
      "cashing_pay_from" => null
      "cashing_pay_to" => null
      "loan_application_survey_pay_type" => null
      "loan_application_survey_pay_from" => null
      "loan_application_survey_pay_to" => null
      "other_payments_sum_type" => null
      "security_type" => null
      "other_payments_sum_percent_type" => null
      "other_payments_name" => null
      "other_payments_periodicity" => 0
      "other_payments_absolute_amount" => null
      "other_payments_to" => null
      "other_payments_from" => null
      "documents_list_area" => null
      "more_special_projects" => null
      "deposit_message" => null
      "activate_date" => null
      "active_date" => "08/22/2018"
      "auto_show_name" => null
      "auto_show_address" => null
      "auto_show_phone" => null
      "created_at" => "2018-08-22 17:55:30"
      "updated_at" => "2018-08-22 17:55:30"
      "repayment_loan_interval_types" => null
      "repayment_percent_interval_types" => null
      "percentage_fixed" => null
      "percentage_changing_from" => null
      "percentage_changing_to" => null
      "percentage_changing_in" => null
      "percentage_changing_concret_to" => "0"
      "percentage_changing_concret_from" => "0"
      "security_types" => null
      "other_payments" => null
      "car_salons" => null
      "special_project_percent" => null
      "documents_list" => null
      "document_name" => null
      "privileged_term_checked" => null
      "checked_repayment_loan_interval_types" => null
      "checked_repayment_percent_interval_types" => null
      "other_payments_checked" => null
      "checked_security_types" => null
      "loan_application_absolute_amount" => null
      "loan_service_absolute_amount" => null
      "pledge_assessment_absolute_amount" => null
      "cashing_pay_absolute_amount" => null
      "pledge_insurance_absolute_amount" => null
      "company_info" => array:33 [
    "id" => 33
        "around_the_clock_working" => null
        "name" => "ccccccccccccccc"
        "type" => 1
        "company_superadmin_id" => 85
        "city" => null
        "extra" => ""
        "identity" => "1"
        "address" => "cccccccccc"
        "phone_number" => "sdfsdf"
        "phone_number_2" => null
        "image" => "company/1526046056.jpg"
        "email" => "dd@gmai.com"
        "website" => null
        "workingDays" => null
        "sundayWorkEndTime" => null
        "sundayWorkStartTime" => null
        "saturdayWorkEndTime" => null
        "saturdayWorkStartTime" => null
        "fridayWorkEndTime" => null
        "fridayWorkStartTime" => null
        "thursdayWorkEndTime" => null
        "thursdayWorkStartTime" => null
        "wednesdayWorkEndTime" => null
        "wednesdayWorkStartTime" => null
        "tuesdayWorkEndTime" => null
        "tuesdayWorkStartTime" => null
        "mondayWorkEndTime" => null
        "mondayWorkStartTime" => null
        "stateEnd" => null
        "stateStart" => null
        "created_at" => "2018-06-18 18:28:56"
        "updated_at" => "2018-06-19 14:51:55"
      ]
      "car_info" => null
      "loan_term_from_periodicity_type_info" => null
      "loan_term_to_periodicity_type_info" => null
    ]
    6 => array:115 [
    "id" => 15
      "company_id" => 33
      "name" => "sadasdsad"
      "copy" => null
      "edit" => null
      "status" => 1
      "curr_row_old_data" => null
      "active_time_type" => null
      "checked_special_projects" => null
      "checked_documents_types" => "2,3"
      "checker_admin_id" => null
      "author_id" => 89
      "belonging_id" => 1
      "car_type" => 1
      "prepayment" => "NULL"
      "loan_amount_from" => "1"
      "loan_amount_to" => "2"
      "prepayment_to" => "4"
      "prepayment_from" => "1"
      "loan_term_from" => "1"
      "loan_term_to" => "2"
      "loan_term_to_in_days" => "60"
      "loan_term_from_in_days" => "1"
      "loan_term_from_periodicity_type" => 1
      "loan_term_to_periodicity_type" => 2
      "privileged_term" => null
      "privileged_term_loan" => null
      "privileged_term_loan_time_type" => null
      "privileged_term_percentage_time_type" => null
      "privileged_term_percentage" => null
      "checked_repayment_types" => "2"
      "providing_type" => 2
      "percentage_type" => 2
      "percentage_rate_type" => null
      "nominal_percentage_rate" => null
      "car_salone_loan_phone" => null
      "car_salone_loan_address" => null
      "car_salone_loan_name" => null
      "service_on_company_website" => "http://cbapro/edit-product/1/1"
      "loan_main_amount_non_payment_case" => "aaaaaaaaaaaaa"
      "loan_main_amount_non_payment_case_old" => null
      "percentage_sum_non_payment_case" => "bbbbbbbbbbbbbbbbbbb"
      "another_non_payments_case" => "cccccccc"
      "another_non_payments_case_old" => null
      "other_non_payment" => "ddddddddddddddddd"
      "security" => null
      "special_projects" => 0
      "special_project_name" => null
      "more_information" => null
      "notarial_ratification_pay" => "6%"
      "notarial_ratification_pay_from" => "1"
      "notarial_ratification_pay_to" => "2"
      "pledge_insurance_pay_type" => null
      "pledge_insurance_pay_for_type" => null
      "pledge_insurance_pay_from" => null
      "pledge_insurance_pay_to" => null
      "loan_service_pay_type" => null
      "loan_service_pay_for_type" => null
      "loan_service_pay_from" => null
      "loan_service_pay_to" => null
      "pledge_assessment_pay_once_type" => null
      "pledge_assessment_pay_from" => null
      "pledge_assessment_pay_to" => null
      "cashing_pay_type" => null
      "cashing_pay_from" => null
      "cashing_pay_to" => null
      "loan_application_survey_pay_type" => null
      "loan_application_survey_pay_from" => null
      "loan_application_survey_pay_to" => null
      "other_payments_sum_type" => null
      "security_type" => null
      "other_payments_sum_percent_type" => null
      "other_payments_name" => null
      "other_payments_periodicity" => 0
      "other_payments_absolute_amount" => null
      "other_payments_to" => null
      "other_payments_from" => null
      "documents_list_area" => null
      "more_special_projects" => null
      "deposit_message" => null
      "activate_date" => 1
      "active_date" => "08/31/2018"
      "auto_show_name" => null
      "auto_show_address" => null
      "auto_show_phone" => null
      "created_at" => "2018-08-23 14:27:51"
      "updated_at" => "2018-08-23 14:27:51"
      "repayment_loan_interval_types" => null
      "repayment_percent_interval_types" => null
      "percentage_fixed" => null
      "percentage_changing_from" => null
      "percentage_changing_to" => null
      "percentage_changing_in" => "1"
      "percentage_changing_concret_to" => null
      "percentage_changing_concret_from" => null
      "security_types" => null
      "other_payments" => null
      "car_salons" => null
      "special_project_percent" => null
      "documents_list" => null
      "document_name" => "sdasdasdasd"
      "privileged_term_checked" => null
      "checked_repayment_loan_interval_types" => "0"
      "checked_repayment_percent_interval_types" => "0"
      "other_payments_checked" => null
      "checked_security_types" => "1,2"
      "loan_application_absolute_amount" => "1"
      "loan_service_absolute_amount" => "2"
      "pledge_assessment_absolute_amount" => "3"
      "cashing_pay_absolute_amount" => "4"
      "pledge_insurance_absolute_amount" => "5"
      "company_info" => array:33 [
    "id" => 33
        "around_the_clock_working" => null
        "name" => "ccccccccccccccc"
        "type" => 1
        "company_superadmin_id" => 85
        "city" => null
        "extra" => ""
        "identity" => "1"
        "address" => "cccccccccc"
        "phone_number" => "sdfsdf"
        "phone_number_2" => null
        "image" => "company/1526046056.jpg"
        "email" => "dd@gmai.com"
        "website" => null
        "workingDays" => null
        "sundayWorkEndTime" => null
        "sundayWorkStartTime" => null
        "saturdayWorkEndTime" => null
        "saturdayWorkStartTime" => null
        "fridayWorkEndTime" => null
        "fridayWorkStartTime" => null
        "thursdayWorkEndTime" => null
        "thursdayWorkStartTime" => null
        "wednesdayWorkEndTime" => null
        "wednesdayWorkStartTime" => null
        "tuesdayWorkEndTime" => null
        "tuesdayWorkStartTime" => null
        "mondayWorkEndTime" => null
        "mondayWorkStartTime" => null
        "stateEnd" => null
        "stateStart" => null
        "created_at" => "2018-06-18 18:28:56"
        "updated_at" => "2018-06-19 14:51:55"
      ]
      "car_info" => array:6 [
    "id" => 1
        "name" => "առաջնային շուկա"
        "icon" => null
        "extra" => null
        "created_at" => null
        "updated_at" => null
      ]
      "loan_term_from_periodicity_type_info" => array:6 [
    "id" => 1
        "name" => "Օր"
        "icon" => null
        "extra" => null
        "created_at" => null
        "updated_at" => null
      ]
      "loan_term_to_periodicity_type_info" => array:6 [
    "id" => 2
        "name" => "Ամիս"
        "icon" => null
        "extra" => null
        "created_at" => null
        "updated_at" => null
      ]
    ]
  ]
]